name: beta docker build and push

on:
  push:
    branches:
      - beta

jobs:
  beta_build_and_push:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - run: git tag beta.$(date +\%y\%m\%d\%H\%M)
      - run: ./docker_build_and_push.sh beta
