name: docker build and push

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@main

      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mebtte/cicada
          short-description: "A multi-user music service for self-hosting."
          readme-filepath: "./docker.md"

      - run: ./docker_build_and_push.sh
